vm: true
runtime: java

application: lazerka-worktimer
module: default
threadsafe: true


# Default
runtime_config:
  jdk: openjdk8
  server: jetty9

network:
  forwarded_ports:
    - 8080 # Default
    #- 8081
    #- 8082:8083
  #instance_tag: <tag-name>
  name: default


resources:
  cpu: .5
  memory_gb: 1.3
  disk_size_gb: 10

#
#health_check:
#  enable_health_check: True
#  check_interval_sec: 5
#  timeout_sec: 4
#  unhealthy_threshold: 2
#  healthy_threshold: 2
#  restart_threshold: 60

#automatic_scaling:
#  min_num_instances: 5
#  max_num_instances: 20
#  cool_down_period_sec: 120 # default value
#  cpu_utilization:
#    target_utilization: 0.5

beta_settings:
  java_quickstart: true


handlers:
- url: /.*
  script: IGNORED
  secure: always
  login: admin
  auth_fail_action: redirect

#env_variables:
#  java.util.logging.config.file: 'WEB-INF/logging.properties'
